### ISSUE TITLE
Surveying the state of L7 protocols in the Cloud Native ecosystem

### ISSUE THREAD

**Issue by beriberikix** [cncf/sig-network#4]
👋 I've been working on a document that captures the state of how [L7 protocols are implemented across the Cloud Native ecosystem](https://docs.google.com/document/d/13wFFC7vIdB2hkxdyT0dSiGgkZTXCDDBeW_GBPqy9Jy0/edit#heading=h.hoz14t7zfu08) with the goal to better understand how one might add new protocols with a native-like-HTTP experience. More details on the motivation @ envoyproxy/envoy#10140.

Would it be interesting to the SIG for me to present my findings at a future meeting? I'd love to continue and expand the discussion!

**Comment by leecalcote** [comment]
@beriberikix yes, indeed. Perhaps, we can get this on the schedule for the May 7th.

**Comment by beriberikix** [comment]
That would be great, thanks! How does the schedule look like for May 7th? How much time should I plan on having?

**Comment by leecalcote** [comment]
We're confirmed for May 7th, @beriberikix. Will 30 minutes suffice?

**Comment by beriberikix** [comment]
Excellent! 30 minutes is plenty - I was planning for ~10 minutes of presentation and the rest discussion. We may even get time back 🙂
